// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pkg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RaftRPCClient is the client API for RaftRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftRPCClient interface {
	// Used when a node in the cluster is first starting up so it can notify a
	// leader what their listening address is.
	JoinCaller(ctx context.Context, in *RemoteNode, opts ...grpc.CallOption) (*JoinReply, error)
	// Invoked by leader to replicate log entries; also used as a heartbeat
	// between leaders and followers.
	AppendEntriesCaller(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesReply, error)
	// Invoked by candidate nodes to request votes from other nodes.
	RequestVoteCaller(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteReply, error)
	// Called by a client to make a request to a Raft node
	ClientRequestCaller(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientReply, error)
}

type raftRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftRPCClient(cc grpc.ClientConnInterface) RaftRPCClient {
	return &raftRPCClient{cc}
}

func (c *raftRPCClient) JoinCaller(ctx context.Context, in *RemoteNode, opts ...grpc.CallOption) (*JoinReply, error) {
	out := new(JoinReply)
	err := c.cc.Invoke(ctx, "/raft.RaftRPC/JoinCaller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftRPCClient) AppendEntriesCaller(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesReply, error) {
	out := new(AppendEntriesReply)
	err := c.cc.Invoke(ctx, "/raft.RaftRPC/AppendEntriesCaller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftRPCClient) RequestVoteCaller(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteReply, error) {
	out := new(RequestVoteReply)
	err := c.cc.Invoke(ctx, "/raft.RaftRPC/RequestVoteCaller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftRPCClient) ClientRequestCaller(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*ClientReply, error) {
	out := new(ClientReply)
	err := c.cc.Invoke(ctx, "/raft.RaftRPC/ClientRequestCaller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftRPCServer is the server API for RaftRPC service.
// All implementations must embed UnimplementedRaftRPCServer
// for forward compatibility
type RaftRPCServer interface {
	// Used when a node in the cluster is first starting up so it can notify a
	// leader what their listening address is.
	JoinCaller(context.Context, *RemoteNode) (*JoinReply, error)
	// Invoked by leader to replicate log entries; also used as a heartbeat
	// between leaders and followers.
	AppendEntriesCaller(context.Context, *AppendEntriesRequest) (*AppendEntriesReply, error)
	// Invoked by candidate nodes to request votes from other nodes.
	RequestVoteCaller(context.Context, *RequestVoteRequest) (*RequestVoteReply, error)
	// Called by a client to make a request to a Raft node
	ClientRequestCaller(context.Context, *ClientRequest) (*ClientReply, error)
	mustEmbedUnimplementedRaftRPCServer()
}

// UnimplementedRaftRPCServer must be embedded to have forward compatible implementations.
type UnimplementedRaftRPCServer struct {
}

func (UnimplementedRaftRPCServer) JoinCaller(context.Context, *RemoteNode) (*JoinReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinCaller not implemented")
}
func (UnimplementedRaftRPCServer) AppendEntriesCaller(context.Context, *AppendEntriesRequest) (*AppendEntriesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendEntriesCaller not implemented")
}
func (UnimplementedRaftRPCServer) RequestVoteCaller(context.Context, *RequestVoteRequest) (*RequestVoteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVoteCaller not implemented")
}
func (UnimplementedRaftRPCServer) ClientRequestCaller(context.Context, *ClientRequest) (*ClientReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientRequestCaller not implemented")
}
func (UnimplementedRaftRPCServer) mustEmbedUnimplementedRaftRPCServer() {}

// UnsafeRaftRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftRPCServer will
// result in compilation errors.
type UnsafeRaftRPCServer interface {
	mustEmbedUnimplementedRaftRPCServer()
}

func RegisterRaftRPCServer(s grpc.ServiceRegistrar, srv RaftRPCServer) {
	s.RegisterService(&RaftRPC_ServiceDesc, srv)
}

func _RaftRPC_JoinCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoteNode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCServer).JoinCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftRPC/JoinCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCServer).JoinCaller(ctx, req.(*RemoteNode))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftRPC_AppendEntriesCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCServer).AppendEntriesCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftRPC/AppendEntriesCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCServer).AppendEntriesCaller(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftRPC_RequestVoteCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCServer).RequestVoteCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftRPC/RequestVoteCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCServer).RequestVoteCaller(ctx, req.(*RequestVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftRPC_ClientRequestCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRPCServer).ClientRequestCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftRPC/ClientRequestCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRPCServer).ClientRequestCaller(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftRPC_ServiceDesc is the grpc.ServiceDesc for RaftRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raft.RaftRPC",
	HandlerType: (*RaftRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinCaller",
			Handler:    _RaftRPC_JoinCaller_Handler,
		},
		{
			MethodName: "AppendEntriesCaller",
			Handler:    _RaftRPC_AppendEntriesCaller_Handler,
		},
		{
			MethodName: "RequestVoteCaller",
			Handler:    _RaftRPC_RequestVoteCaller_Handler,
		},
		{
			MethodName: "ClientRequestCaller",
			Handler:    _RaftRPC_ClientRequestCaller_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft_rpc.proto",
}
